### ISSUE TITLE
Cmake version error

### ISSUE THREAD

**Issue by mbelda** [ucb-bar/onnxruntime-riscv#65]
I am trying to build the repo on firesim.
I am currently running the command ./build.sh --parallel --for_firesim, but it founds an error on the cmake version.
I have already updated it but it keeps showing the error even if it has no coherence:

CMake Error at CMakeLists.txt:6 (cmake_minimum_required):
  CMake 3.13 or higher is required.  You are running version 3.6.2

¿How can I fix this?

Thanks in advance.
Regards, Majo.

**Comment by KUEE1080** [comment]
I actually had the same issue when I was installing, but I followed the procedure explained in the website below and it worked. Since it is written in korean, I would recommend you to use google translate function inside google chrome.

https://somjang.tistory.com/entry/Ubuntu-CMake-%EC%97%85%EB%8D%B0%EC%9D%B4%ED%8A%B8-%ED%95%98%EB%8A%94-%EB%B0%A9%EB%B2%95

**Comment by mbelda** [comment]
I finally solved it with the following.
I realised I had the cmake version 3.6.2 installed on usr/local/bin but the old one was in usr/bin.
So I created a symlink in /usr/bin to the local one, so now everything must use the new version and, effectively, now it works.

Thank you!

**Comment by mbelda** [comment]
I solved it. 
Apparently the version 3.6 is too much new. I just installed the 3.23 and it work fine.
